// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: little-tg.proto

package littletgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tgmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Unique ID number for this person.
}

func (x *Tgmessage) Reset() {
	*x = Tgmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_little_tg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tgmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tgmessage) ProtoMessage() {}

func (x *Tgmessage) ProtoReflect() protoreflect.Message {
	mi := &file_little_tg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tgmessage.ProtoReflect.Descriptor instead.
func (*Tgmessage) Descriptor() ([]byte, []int) {
	return file_little_tg_proto_rawDescGZIP(), []int{0}
}

func (x *Tgmessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Tgmessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_little_tg_proto protoreflect.FileDescriptor

var file_little_tg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x2d, 0x74, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x74, 0x67, 0x22, 0x41, 0x0a, 0x09, 0x74,
	0x67, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x3c,
	0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x74, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_little_tg_proto_rawDescOnce sync.Once
	file_little_tg_proto_rawDescData = file_little_tg_proto_rawDesc
)

func file_little_tg_proto_rawDescGZIP() []byte {
	file_little_tg_proto_rawDescOnce.Do(func() {
		file_little_tg_proto_rawDescData = protoimpl.X.CompressGZIP(file_little_tg_proto_rawDescData)
	})
	return file_little_tg_proto_rawDescData
}

var file_little_tg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_little_tg_proto_goTypes = []interface{}{
	(*Tgmessage)(nil), // 0: littletg.tgmessage
}
var file_little_tg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_little_tg_proto_init() }
func file_little_tg_proto_init() {
	if File_little_tg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_little_tg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tgmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_little_tg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_little_tg_proto_goTypes,
		DependencyIndexes: file_little_tg_proto_depIdxs,
		MessageInfos:      file_little_tg_proto_msgTypes,
	}.Build()
	File_little_tg_proto = out.File
	file_little_tg_proto_rawDesc = nil
	file_little_tg_proto_goTypes = nil
	file_little_tg_proto_depIdxs = nil
}
